"""Curated catalogue of Latin American and international news outlets.

Discovery is domain-filtered through GDELT. Entries are a watchlist, not a
ranking. Domains already present were left as they were; additions are outlets
from the desk list and the sample briefings whose domains were checked.
"""

from __future__ import annotations

from .models import Publication


def _p(name: str, domain: str, market: str, scope: str = "latin_america") -> Publication:
    return Publication(name=name, domain=domain.lower(), market=market, scope=scope)


LATIN_AMERICAN_PUBLICATIONS = [
    _p("Clarín", "clarin.com", "Argentina"),
    _p("La Nación", "lanacion.com.ar", "Argentina"),
    _p("Página/12", "pagina12.com.ar", "Argentina"),
    _p("Infobae", "infobae.com", "Argentina"),
    _p("Perfil", "perfil.com", "Argentina"),
    _p("Ámbito Financiero", "ambito.com", "Argentina"),
    _p("La Derecha Diario", "derechadiario.com.ar", "Argentina"),
    _p("Filo News", "filo.news", "Argentina"),
    _p("El Deber", "eldeber.com.bo", "Bolivia"),
    _p("La Razón", "la-razon.com", "Bolivia"),
    _p("Los Tiempos", "lostiempos.com", "Bolivia"),
    _p("Brújula Digital", "brujuladigital.net", "Bolivia"),
    _p("Folha de S.Paulo", "folha.uol.com.br", "Brazil"),
    _p("O Globo", "oglobo.globo.com", "Brazil"),
    _p("G1", "g1.globo.com", "Brazil"),
    _p("O Estado de S. Paulo", "estadao.com.br", "Brazil"),
    _p("Valor Econômico", "valor.globo.com", "Brazil"),
    _p("Correio Braziliense", "correiobraziliense.com.br", "Brazil"),
    _p("Poder360", "poder360.com.br", "Brazil"),
    _p("Gazeta do Povo", "gazetadopovo.com.br", "Brazil"),
    _p("UOL", "uol.com.br", "Brazil"),
    _p("R7", "r7.com", "Brazil"),
    _p("El Mercurio / Emol", "emol.com", "Chile"),
    _p("La Tercera", "latercera.com", "Chile"),
    _p("El Mostrador", "elmostrador.cl", "Chile"),
    _p("Diario Financiero", "df.cl", "Chile"),
    _p("El Líbero", "ellibero.cl", "Chile"),
    _p("CIPER", "ciperchile.cl", "Chile"),
    _p("El Tiempo", "eltiempo.com", "Colombia"),
    _p("El Espectador", "elespectador.com", "Colombia"),
    _p("Semana", "semana.com", "Colombia"),
    _p("La República", "larepublica.co", "Colombia"),
    _p("La Silla Vacía", "lasillavacia.com", "Colombia"),
    _p("El Colombiano", "elcolombiano.com", "Colombia"),
    _p("El Heraldo", "elheraldo.co", "Colombia"),
    _p("La Nación", "nacion.com", "Costa Rica"),
    _p("CRHoy", "crhoy.com", "Costa Rica"),
    _p("Delfino", "delfino.cr", "Costa Rica"),
    _p("Semanario Universidad", "semanariouniversidad.com", "Costa Rica"),
    _p("Granma", "granma.cu", "Cuba"),
    _p("14ymedio", "14ymedio.com", "Cuba"),
    _p("Diario de Cuba", "diariodecuba.com", "Cuba"),
    _p("El Toque", "eltoque.com", "Cuba"),
    _p("Listín Diario", "listindiario.com", "Dominican Republic"),
    _p("Diario Libre", "diariolibre.com", "Dominican Republic"),
    _p("Acento", "acento.com.do", "Dominican Republic"),
    _p("El Universo", "eluniverso.com", "Ecuador"),
    _p("El Comercio", "elcomercio.com", "Ecuador"),
    _p("Primicias", "primicias.ec", "Ecuador"),
    _p("Expreso", "expreso.ec", "Ecuador"),
    _p("Plan V", "planv.com.ec", "Ecuador"),
    _p("GK", "gk.city", "Ecuador"),
    _p("La Prensa Gráfica", "laprensagrafica.com", "El Salvador"),
    _p("El Diario de Hoy", "elsalvador.com", "El Salvador"),
    _p("El Faro", "elfaro.net", "El Salvador"),
    _p("Revista Factum", "revistafactum.com", "El Salvador"),
    _p("Prensa Libre", "prensalibre.com", "Guatemala"),
    _p("Soy502", "soy502.com", "Guatemala"),
    _p("Plaza Pública", "plazapublica.com.gt", "Guatemala"),
    _p("No-Ficción", "no-ficcion.com", "Guatemala"),
    _p("República GT", "republica.com", "Guatemala"),
    _p("Le Nouvelliste", "lenouvelliste.com", "Haiti"),
    _p("Haiti Libre", "haitilibre.com", "Haiti"),
    _p("La Prensa", "laprensa.hn", "Honduras"),
    _p("El Heraldo", "elheraldo.hn", "Honduras"),
    _p("Contracorriente", "contracorriente.red", "Honduras"),
    _p("Criterio.hn", "criterio.hn", "Honduras"),
    _p("El Universal", "eluniversal.com.mx", "Mexico"),
    _p("Reforma", "reforma.com", "Mexico"),
    _p("Milenio", "milenio.com", "Mexico"),
    _p("La Jornada", "jornada.com.mx", "Mexico"),
    _p("Excélsior", "excelsior.com.mx", "Mexico"),
    _p("El Financiero", "elfinanciero.com.mx", "Mexico"),
    _p("Animal Político", "animalpolitico.com", "Mexico"),
    _p("Proceso", "proceso.com.mx", "Mexico"),
    _p("Aristegui Noticias", "aristeguinoticias.com", "Mexico"),
    _p("La Prensa", "laprensani.com", "Nicaragua"),
    _p("Confidencial", "confidencial.digital", "Nicaragua"),
    _p("Divergentes", "divergentes.com", "Nicaragua"),
    _p("El 19 Digital", "el19digital.com", "Nicaragua"),
    _p("La Prensa", "prensa.com", "Panama"),
    _p("La Estrella de Panamá", "laestrella.com.pa", "Panama"),
    _p("ABC Color", "abc.com.py", "Paraguay"),
    _p("Última Hora", "ultimahora.com", "Paraguay"),
    _p("El Comercio", "elcomercio.pe", "Peru"),
    _p("La República", "larepublica.pe", "Peru"),
    _p("Gestión", "gestion.pe", "Peru"),
    _p("Perú21", "peru21.pe", "Peru"),
    _p("IDL-Reporteros", "idl-reporteros.pe", "Peru"),
    _p("RPP", "rpp.pe", "Peru"),
    _p("El Nuevo Día", "elnuevodia.com", "Puerto Rico"),
    _p("Primera Hora", "primerahora.com", "Puerto Rico"),
    _p("El País", "elpais.com.uy", "Uruguay"),
    _p("El Observador", "elobservador.com.uy", "Uruguay"),
    _p("La Diaria", "ladiaria.com.uy", "Uruguay"),
    _p("Búsqueda", "busqueda.com.uy", "Uruguay"),
    _p("El Nacional", "elnacional.com", "Venezuela"),
    _p("El Universal", "eluniversal.com", "Venezuela"),
    _p("TalCual", "talcualdigital.com", "Venezuela"),
    _p("Efecto Cocuyo", "efectococuyo.com", "Venezuela"),
    _p("El Pitazo", "elpitazo.net", "Venezuela"),
    _p("Armando.info", "armando.info", "Venezuela"),
    _p("Prodavinci", "prodavinci.com", "Venezuela"),
    _p("Runrun.es", "runrun.es", "Venezuela"),
    _p("Globovisión", "globovision.com", "Venezuela"),
    _p("teleSUR", "telesurtv.net", "Venezuela"),
    _p("Banca y Negocios", "bancaynegocios.com", "Venezuela"),
    _p("Ministerio de Relaciones Exteriores", "mppre.gob.ve", "Venezuela"),
]

INTERNATIONAL_PUBLICATIONS = [
    _p("Reuters", "reuters.com", "International", "international"),
    _p("Associated Press", "apnews.com", "International", "international"),
    _p("BBC News", "bbc.com", "United Kingdom", "international"),
    _p("The Guardian", "theguardian.com", "United Kingdom", "international"),
    _p("Financial Times", "ft.com", "United Kingdom", "international"),
    _p("The Economist", "economist.com", "United Kingdom", "international"),
    _p("The Times", "thetimes.com", "United Kingdom", "international"),
    _p("The New York Times", "nytimes.com", "United States", "international"),
    _p("The Washington Post", "washingtonpost.com", "United States", "international"),
    _p("The Wall Street Journal", "wsj.com", "United States", "international"),
    _p("Los Angeles Times", "latimes.com", "United States", "international"),
    _p("Bloomberg", "bloomberg.com", "United States", "international"),
    _p("Politico", "politico.com", "United States", "international"),
    _p("CNN", "cnn.com", "United States", "international"),
    _p("The Globe and Mail", "theglobeandmail.com", "Canada", "international"),
    _p("CBC News", "cbc.ca", "Canada", "international"),
    _p("El País", "elpais.com", "Spain", "international"),
    _p("El Mundo", "elmundo.es", "Spain", "international"),
    _p("Le Monde", "lemonde.fr", "France", "international"),
    _p("France 24", "france24.com", "France", "international"),
    _p("Deutsche Welle", "dw.com", "Germany", "international"),
    _p("Al Jazeera", "aljazeera.com", "Qatar", "international"),
    _p("Nikkei Asia", "asia.nikkei.com", "Japan", "international"),
    _p("South China Morning Post", "scmp.com", "Hong Kong", "international"),
    _p("The Sydney Morning Herald", "smh.com.au", "Australia", "international"),
    _p("ABC News Australia", "abc.net.au", "Australia", "international"),
    _p("AFP", "afp.com", "France", "international"),
    _p("EFE", "efe.com", "Spain", "international"),
    _p("Bloomberg Línea", "bloomberglinea.com", "United States", "international"),
    _p("Americas Quarterly", "americasquarterly.org", "United States", "international"),
    _p("Diálogo Américas", "dialogo-americas.com", "United States", "international"),
    _p("El Cato", "elcato.org", "United States", "international"),
    _p("PanAm Post", "panampost.com", "United States", "international"),
    _p("El American", "elamerican.com", "United States", "international"),
    _p("CNN Español", "cnnespanol.cnn.com", "United States", "international"),
    _p("El Nuevo Herald", "elnuevoherald.com", "United States", "international"),
    _p("Voz de América", "vozdeamerica.com", "United States", "international"),
    _p("MercoPress", "mercopress.com", "International", "international"),
]

PUBLICATIONS = LATIN_AMERICAN_PUBLICATIONS + INTERNATIONAL_PUBLICATIONS
PUBLICATION_BY_DOMAIN = {publication.domain: publication for publication in PUBLICATIONS}


def match_publication(domain: str) -> Publication | None:
    """Match a host returned by GDELT, accepting www and subdomain variants."""
    domain = domain.lower().removeprefix("www.")
    exact = PUBLICATION_BY_DOMAIN.get(domain)
    if exact:
        return exact
    matches = [p for p in PUBLICATIONS if domain == p.domain or domain.endswith("." + p.domain)]
    return max(matches, key=lambda p: len(p.domain), default=None)

